### ISSUE TITLE
NANs o no NANs esa es la cuestion (gaussian_kde)

### ISSUE THREAD

**Issue by PabloPsicotico** [aloctavodia/EBAD#1]
En el [script] (https://github.com/aloctavodia/EBAD/blob/master/01_estad%C3%ADstica/hdi.py) de 01_estadística, en la línea 7 (density = kde.gaussian_kde(trace)), la función scipy.stats.gaussian_kde no acepta nans, tal vez convenga aclararlo en la descripción de la función o eliminarlos antes.

**Comment by aloctavodia** [comment]
Gracias por la notificación, en el contexto en el que fue pensada la función esta nunca espera nans. De todas formas, estaria bueno generalizar la función ya que creo que puede ser util en otros contextos (como en tu caso). En cuanto pueda lo hago. Gracias!
